app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, EmailField
from wtforms.validators import DataRequired, Length


class CustomerSigninForm(FlaskForm):
    email = EmailField('Customer Email', 
                           validators=[DataRequired('email required!!')])
    submit = SubmitField('SIGN IN')


class CustomerSignupForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = EmailField('Customer Email', 
                           validators=[DataRequired('email required!!')])
    submit = SubmitField('SIGN UP')

app/dashboard/__init__.py
from flask import Blueprint

dashboard_bp = Blueprint('dashboard', __name__)

app/dashboard/routes.py
from flask import render_template, request, redirect, url_for
from flask_login import current_user, login_required

from app import login, db
from app.models import Customer, Rental, Video, Staff
from app.dashboard.errors import NotFoundException, AlreadyExistsException
from app.dashboard import dashboard_bp
from app.dashboard.forms import CustomerSigninForm, CustomerSignupForm


@dashboard_bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    rentals = []
    msg = ''
    title = 'Dashboard'

    if request.method == 'GET':
        rentals = Rental.query.order_by(Rental.date.desc()).all()
        return_state = {}
        if request.args.get('msg'):
            msg = request.args.get('msg')
        
        if not rentals:
            msg += ' No Rentals to display'

        if msg and msg!='Success':
            return render_template('dashboard/index.html', title=title, rentals=rentals, msg=msg)
        
        import datetime
        default_date = datetime.datetime.utcnow()\
            .replace(year=1000, month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
        
        for rental in rentals: 
            return_state[rental] = rental.date_returned!=default_date

    return render_template('dashboard/index.html', rentals=rentals, return_state=return_state, msg=msg, title=title)    



@dashboard_bp.route('/signin', methods=['GET', 'POST'])
def signin():
    msg = ''
    title = 'Customer Sign In'
    customer_signin = CustomerSigninForm()

    # when email is submitted, validate staff
    if customer_signin.is_submitted():
        customer = Customer.query.filter(Customer.email==customer_signin.email.data).first()
        if not customer:
            msg = 'Customer not Found'
            return render_template('dashboard/signin.html', title=title, customer_signin=customer_signin)
    
        return redirect(url_for('rental.index', customer_id=customer.customer_id))
    
    return render_template('dashboard/signin.html', title=title, customer_signin=customer_signin)


@dashboard_bp.route('signup', methods=['POST', 'GET'])
def signup():
    customer_signup = CustomerSignupForm()
    msg = ''
    title = 'Sign Up'
    customer = Customer.query.filter(Customer.customer_id==0).first()

    # when new customer details are submitted, validate and add new signup then 
    # go to rental page
    if customer_signup.is_submitted():
        if Customer.query.filter(Customer.email==customer_signup.email.data).first():
            msg = 'Customer already exists!!'
            return render_template('dashboard/signup.html', title=title, customer_signup=customer_signup, msg=msg)
        
        customer = Customer(first_name=customer_signup.first_name.data, last_name=customer_signup.last_name.data,
                            email=customer_signup.email.data)
        
        db.session.add(customer)
        db.session.commit()
            
        return redirect(url_for('rental.index', customer_id=customer.customer_id))
    
    return render_template('dashboard/signup.html', title=title, customer_signup=customer_signup)

    

app/templates/dashboard/index.html
{% extends "base.html" %}

{% block content %}
<h1>Dashboard</h1>
<ul style="list-style: circle;">
    <li><a href="{{ url_for('dashboard.signin') }}">New Rental Transaction</a></li>
    <li><a href="{{ url_for('dashboard.signup') }}">New Customer Account</a></li>
</ul>
<h2>Video Rentals</h2>
{% if rentals %}
<table>
    <thead>
        <th>Rental ID</th>
        <th>Video Title</th>
        <th>Customer Name</th>
        <th>Amount Paid</th>
        <th>Date</th>
        <th>Due Date</th>
        <th>Date Returned</th>
    </thead>
    <tbody>
    {% for rental in rentals %}
        <tr>
            <td>{{ rental.rental_id }}</td>
            {% if rental.video.video_title=="Deleted" %}
            <td><span style="color: red">{{ rental.video.video_title }}</span></td>
            {% else %}
            <td>{{ rental.video.video_title }}</td>
            {% endif %}
            <td>{{ rental.customer.first_name }} {{ rental.customer.last_name }}</td>
            <td>{{ rental.video.unit_price + rental.video.unit_price*0.1 }}</td>
            <td>{{ rental.date }}</td>
            <td>{{ rental.due_date }}</td>
            {% if return_state[rental] %}
            <td>{{ rental.date_returned }}</td>
            {% else %} <td><span style="color: red;">Not Returned</span></td>
            {% endif %}
        </tr>
    {% endfor %}    
    </tbody>
</table>
{% else %} <p style="font-style: italic;">No Rentals To Display</p>
{% endif %}
{% endblock content %}

app/templates/dashboard/signin.html
{% extends "base.html" %}

{% block content %}
<h1>Sign Customer In</h1>
<form method="POST" name="customer_signin">
    {{ customer_signin.hidden_tag() }}
    {{ customer_signin.email.label }}<br>
    {{ customer_signin.email(id="emailField", placeholder="Enter customer email here") }}<br>
    <span style="color: red">{{ msg }}</span><br>
    {{ customer_signin.submit(id="submitField") }}<br><br>
    Not registered? <a href="{{ url_for('dashboard.signup') }}">sign up</a>
</form>

{% endblock content %}

app/templates/dashboard/signup.html
{% extends "base.html" %}

{% block content %}
<h1>Sign Customer Up</h1>
<form method="POST" name="customer_signup">
    {{ customer_signup.hidden_tag() }}
    {{ customer_signup.first_name.label }}<br>
    {{ customer_signup.first_name(id="firstNameField", placeholder="Enter first name here") }}<br><br>
    {{ customer_signup.last_name.label }}<br>
    {{ customer_signup.last_name(id="lastNameField", placeholder="Enter last name here") }}<br><br>
    {{ customer_signup.email.label }}<br>
    {{ customer_signup.email(id="emailField", placeholder="Enter customer email here") }}<br><br>
    <span style="color: red">{{ msg }}</span><br>
    {{ customer_signup.submit(id="submitField") }}
</form>

{% endblock content %}