app/videos/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, IntegerField, SelectField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Length, NumberRange
import datetime
from app.models import Genre

class NewVideoForm(FlaskForm):
    video_title = StringField('Video Title', validators=[DataRequired(), Length(max=60)])
    unit_price = DecimalField('Unit Price', validators=[DataRequired()])
    release_year = IntegerField('Release Year', validators=[DataRequired(), \
                                                           NumberRange(min=1900, max=datetime.date.today().year)])
    genre = SelectField('Genre')
    submit = SubmitField('ADD VIDEO')


class VideoForm(FlaskForm):
    video_title = StringField('Video Title', validators=[DataRequired(), Length(max=60)])
    unit_price = DecimalField('Unit Price', validators=[DataRequired()])
    release_year = IntegerField('Release Year', validators=[DataRequired(), \
                                                           NumberRange(min=1900, max=datetime.date.today().year)])
    genre = SelectField('Genre')
    password = PasswordField('Enter staff password to update changes')
    show_password = BooleanField('Show Password')
    submit = SubmitField('UPDATE VIDEO')

class DeleteForm(FlaskForm):
    password = PasswordField('Enter staff password to delete videos')
    show_password = BooleanField('Show Password')
    submit = SubmitField('DELETE')

app/videos/__init__.py
from flask import Blueprint

videos_bp = Blueprint('videos', __name__)

app/videos/routes.py
from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
from app import db
from app.models import Customer, Rental, Video, Staff, Genre
from app.videos import videos_bp
from app.videos.forms import NewVideoForm, VideoForm, DeleteForm
from app.videos.errors import NotFoundException


@videos_bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    # view all movies
    available = {}
    errmsg = ''
    msg = ''
    title = 'Video Catalog'
    
    videos = Video.query.filter(Video.video_title!='Deleted').all()

    if not videos:
        errmsg = 'There are currently no Videos'
        
    if errmsg:
        return render_template('videos/index.html', title=title, errmsg=errmsg)
    import datetime
    default_date = datetime.datetime.utcnow()\
            .replace(year=1000, month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
    
    for video in videos:
        rental = video.rentals.filter(Rental.date_returned==default_date).first()
        if rental:
            available[video] = False
        else:
            available[video] = True

    if request.args.get('msg'):
        msg = request.args.get('msg')

    return render_template('videos/index.html', title=title, videos=videos,\
                            available=available, msg=msg)


@videos_bp.route('/new', methods=['GET', 'POST'])
def new_video():
    msg = ''
    new_video_form = NewVideoForm()
    new_video_form.genre.choices = [(genre.genre_id, genre.genre_name) for genre in Genre.query.all()]
    title = 'Add Video'

    if new_video_form.is_submitted():
        
        if Video.query.filter(Video.video_title==new_video_form.video_title.data).first():
            msg = 'Video already Exists'
            return render_template('videos/new_video.html', new_video_form=new_video_form, msg=msg)
        
        genre = Genre.query.filter(Genre.genre_id==new_video_form.genre.data).first()
        
        video = Video(video_title=new_video_form.video_title.data, \
                      release_year=new_video_form.release_year.data, \
                        unit_price=new_video_form.unit_price.data, genre=genre)
        db.session.add(video)
        db.session.commit()
        msg = f'{video.video_title} is added successfully'
        return redirect(url_for('videos.index', msg=msg))
    
    return render_template('videos/new_video.html', new_video_form=new_video_form, msg=msg, title=title)


@videos_bp.route('/update/<int:video_id>', methods=['GET', 'POST'])
def update_video(video_id):
    msg = ''
    title = 'Update Video'
    video = Video.query.filter(Video.video_id==video_id).first()
    video_form = VideoForm()
    video_form.genre.choices = [(genre.genre_id, genre.genre_name) for genre in Genre.query.all()]
    
    if request.method == 'GET':
        pass
        # video_form.genre.d = video.genre.genre_id

    if request.method == 'POST':
        if video_form.is_submitted():

            if not current_user.check_password(video_form.password.data):
                return render_template('videos/update_video.html', title=title, video_form=video_form, video=video)

            video.video_title = video_form.video_title.data
            video.release_year = video_form.release_year.data
            video.unit_price = video_form.unit_price.data
            video.genre = Genre.query.filter(Genre.genre_id==video_form.genre.data).first()

            db.session.add(video)
            db.session.commit()

            return redirect(url_for('videos.index'))

    return render_template('videos/update_video.html', title=title, video_form=video_form, video=video)


@videos_bp.route('/delete/<int:video_id>', methods=['GET', 'POST'])
def delete_video(video_id):
    delete_form = DeleteForm()
    video = Video.query.filter(Video.video_id==video_id).first()
    title = 'Delete Video'

    if request.method == 'POST':
        if not current_user.check_password(delete_form.password.data):
            return render_template('videos/delete_video.html', delete_form=delete_form, video=video) 

        video.video_title='Deleted'
        video.release_year=0
        for rental in video.rentals:
            rental.date_returned = None
            rental.date_due = None
        
        db.session.add(video)
        
        db.session.commit()
        return redirect(url_for('videos.index'))
    
    return render_template('videos/delete_video.html',title=title, delete_form=delete_form, video=video)

app/templates/videos/delete_video.html
{% extends "base.html" %}

{% block content %}
<h2>Are You Sure You want to delete {{ video.video_title }}?</h2>
<form method="POST">
    {{ delete_form.password.label }} <br>
    {{ delete_form.password(id="passwordField") }} <br>
    {{ delete_form.show_password(id="showPasswordField", onclick="showPasswordHandler()") }} {{ delete_form.show_password.label }} <br>
    {{ delete_form.submit() }}
</form>
<p>By clicking delete, you agree to permanently erase video information </p>
<script>
    const showPasswordField = document.querySelector("#showPasswordField")
    const passwordField = document.querySelector("#passwordField")
    
    showPasswordHandler = (e) => {
        if (showPasswordField.checked == true){
            passwordField.type = 'text';
        } else{
            passwordField.type = 'password';
        }
    }
</script>
{% endblock content %}

app/templates/videos/index.html
{% extends "base.html" %}

{% block content %}
<h1>Video Catalog</h1>
{% if msg %}
<p style="color:green">{{msg}}</p>
{% endif %}
{% if errmsg %}
<p style="color:red">{{errmsg}}</p>
{% endif %}
<a href="{{ url_for('videos.new_video') }}">New Video</a>
<table>
    <tr>
        <th>Video ID</th>
        <th>Video Title</th>
        <th>Unit Price</th>
        <th>Genre</th>
        <th>Release Year</th>
        <th>Is Available</th>
    </tr>
    {% for video in videos %}
        <tr>
            <td>{{ video.video_id }}</td>
            <td>{{ video.video_title }}</td>
            <td>{{ video.unit_price }}</td>
            <td>{{ video.genre.genre_name }}</td>
            <td>{{ video.release_year }}</td>
            <td>
                {% if available[video] %}
                <span style="color: green;">Yes</span>
                {% else %}
                <span style="color: red;">No</span>
                {% endif %}
            </td>
            <td><a href="{{url_for('videos.update_video', video_id=video.video_id)}}">Update</a></td>
            <td><a href="{{url_for('videos.delete_video', video_id=video.video_id)}}">Delete</a></td>
        </tr>
    {% endfor %}
</table>
<script>
    function confirmDelete(){
        var results = confirm("Are you sure you want delete?");

        if(result == true){
            return true;
        }
        else{
            return false;
        }
    }
</script>
{% endblock content %}

app/templates/videos/new_video.html
{% extends "base.html" %}

{% block content %}
<h1>Add A New Video</h1>
<form name="video_form" method="POST" onsubmit="confirmChanges()">
    {{ new_video_form.hidden_tag() }}
    {{ new_video_form.video_title.label }} <br>
    {{ new_video_form.video_title(placeholder="Enter a video title here") }} <br><br>
    {{ new_video_form.unit_price.label }} <br>
    {{ new_video_form.unit_price(placeholder="Enter unit price here") }} <br><br>
    {{ new_video_form.release_year.label }} <br>
    {{ new_video_form.release_year(placeholder="Enter release year here") }} <br><br>
    {{ new_video_form.genre.label }} <br>
    {{ new_video_form.genre() }} <br><br>
    {{ new_video_form.submit(id="submitBtn") }}
</form>
<script>
    function confirmChanges(){
        var results = confirm("Are you sure you want to continue?");

        if(result == true){
            return true;
        }
        else{
            return false;
        }
    }
</script>
{% endblock content %}

app/templates/videos/update_video.html
{% extends "base.html" %}

{% block content %}
<h1>Update Video</h1>
<form name="video_form" method="POST" onsubmit="confirmChanges()">
    {{ video_form.hidden_tag() }}
    {{ video_form.video_title.label }}<br>
    {{ video_form.video_title(value=video.video_title) }}<br><br>
    {{ video_form.unit_price.label }}<br>
    {{ video_form.unit_price(value=video.unit_price) }}<br><br>
    {{ video_form.release_year.label }} <br>
    {{ video_form.release_year(value=video.release_year) }} <br><br>
    {{ video_form.genre.label }} <br>
    {{ video_form.genre(value=video.genre.genre_id) }}<br><br>
    {{ video_form.password.label }} <br>
    {{ video_form.password(id="passwordField") }} <br>
    {{ video_form.show_password(id="showPasswordField", onclick="showPasswordHandler()") }} {{ video_form.show_password.label }} <br><br>
    {{ video_form.submit }}
</form>
<script>
    const showPasswordField = document.querySelector("#showPasswordField")
    const passwordField = document.querySelector("#passwordField")
    
    showPasswordHandler = (e) => {
        if (showPasswordField.checked == true){
            passwordField.type = 'text';
        } else{
            passwordField.type = 'password';
        }
    }
</script>
{% endblock content %}